version: '3.8'

services:
  db:
    image: postgres:13
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  automobile_service:
    build: ./automobile_service
    command: gunicorn automobile_service.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./automobile_service:/code
      - media_data:/code/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      DEBUG: "1"

  email_service:
    build: ./email_service
    command: gunicorn email_service.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - ./email_service:/code
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
    environment:
      DEBUG: "1"

  email_worker:
    build: ./email_service
    command: celery -A email_service worker -l info
    depends_on:
      - email_service
      - rabbitmq
    environment:
      DEBUG: "1"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
  media_data:
